defaults:
  - /model/placements/shaper/shape_dict@placements.shape_dict: sandbox

_target_: src.inference.captcha_encoder.marionette_captcha_guide
_partial_: true
backbone:
  _target_: src.inference.captcha_encoder.MarioNetteBackbone
  hidden_dims: [16, 32, 64]
  rngs:
    _target_: flax.nnx.Rngs
    default: 3456
backgrounder: null
color_finder:
  _target_: src.inference.captcha_encoder.MarioNetteColorFinder
  backbone_channels: 64
  rngs:
    _target_: flax.nnx.Rngs
    default: 5678
placements:
  _target_: src.inference.captcha_encoder.MarioNettePlacer
  backbone_channels: 64
  img_h: 80
  img_w: 80
  kh: 38
  kw: 26
  mark_temperature: 1.
  rngs:
    _target_: flax.nnx.Rngs
    default: 9012
  stride: 1
  switch_bias: -4.0
  switch_temperature: 1.
