defaults:
  - placements/shaper/shape_dict@placements.shape_dict: sandbox

_target_: src.model.model.marionette_captcha_model
_partial_: true
backgrounder: null
placements:
  _target_: src.model.model.BayesianMarioNettePlacements
  alpha_sharpness: 5.0
  img_h: 80
  img_w: 80
  kh: 38
  kw: 26
  mark_temperature: 1.
  rngs:
    _target_: flax.nnx.Rngs
    default: 5678
  stride: 1
  switch_temperature: 1.
