defaults:
  - _self_
  - data: captcha
  - guide: marionette_captcha_encoder
  - learner: graphical
  - model: marionette_captcha
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "train"
tags: ["dev"]
train: True
test: True
ckpt_path: null
optimized_metric: "loss"
seed: 1234
